org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.0
loader_version_range=[47,)
minecraft_version_range=[1.20.1,1.21)

mod_version=1.0.0
maven_group=com.example.rpgminecraft
archives_base_name=forge
mod_id=forge
mod_name=Forge
mod_description=Adds a shootable RPG launcher with impact explosions.
